### PR TITLE
RHMAP-21645 - Upgrade mongodb to 2.2.33 ( minor version )

### PR DESCRIPTION
**Pull request by camilamacedo86**
# Jira link(s)
https://issues.jboss.org/browse/RHMAP-21645

# What
 Upgrade mogodb to 2.2.33 ( minor version bumped )

# Why
- To solve CEVs

# How
* `npm install --save --save-exact mogodb@2.2.33`

# Verification Steps
Check if the CI will finish with success it did not have breakages

## Checklist:
- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Review by damienomurchu — APPROVED** [review]
LGTM

**Comment by grdryn** [comment]
@camilamacedo86 @damienomurchu Note that in the newer versions of the MongoDB driver that's updated here, if it's connecting to a replica set, the `replicaset=<replicaset name>` parameter needs to be specified on the connection string. We've just hit this in https://github.com/fheng/fh-supercore/pull/1146, so just thought I'd highlight it here. I'm not sure if it affects this project or not, since I don't know how this one works really.

**Comment by camilamacedo86** [comment]
Hi @grdryn I made a comment in the JIRA which follows. 

[~grdryn] could it not be an issue related to the changes performed in the script related to this setup?

* https://github.com/fheng/rhmap-ansible/commit/1bdf367047ffc3bbbb31a1ddbad0f41b8aa1d9a0
* https://github.com/fheng/rhmap-ansible/commit/50a71aeb45efa089f249ff8550bb32fd0a09bf98

Also, if it is regarding the lib could you try the version 2.2.33 of this lib? Shows that a bug related to it was solved here : https://github.com/mongodb/node-mongodb-native/commit/9a7073243de645f0d4e787beb4008fe78bc039dc . And the version 2.1.13 as the lower ones has CVEs. See <https://github.com/mongodb/node-mongodb-native/compare/V2.2.13...v2.2.33>

**Comment by camilamacedo86** [comment]
Added a comment in https://issues.jboss.org/browse/RHMAP-21743 for we check it and if be required revert this one. Also, could you link there the JIRA that you will create regards the replicaset param?

**Pull request merged**
